package com.intelliinvest.server;

import com.intelliinvest.server.util.SignalGenerator;

public class StockSignalGeneratorMain {

	public static void main(String[] args) {
		
		String[] codes = {
				"RANEHOLDIN",
				"ADSL",
				"LAKPRE",
				"FCSSOFT",
				"BHARATGEAR",
				"ZODJRDMKJ",
				"PROVOGE",
				"UMESLTD",
				"ADORWELD",
				"ARVINDREM",
				"ZUARI",
				"WELPROJ",
				"INDUSFILA",
				"SUPREMEINF",
				"PRITHVI",
				"BLUECOAST",
				"RAJOIL",
				"PERIATEA",
				"EUROMULTI",
				"BOSCHLTD",
				"EMPEESUG",
				"NBVENTURES",
				"ALLSEC",
				"NAVNETEDUL",
				"SOMATEX",
				"UBENGG",
				"SMOBILITY",
				"SRHHYPOLTD",
				"EMAMILTD",
				"GENUSPOWER",
				"SUJANATWR",
				"EDUCOMP",
				"ICSA",
				"ALMONDZ",
				"KGL",
				"BEML",
				"RANKLIN",
				"STINDIA",
				"MANALIPETC",
				"KFA",
				"FSL",
				"PPAP",
				"SALONACOT",
				"GANESHHOUC",
				"BEL",
				"ANDHRABANK",
				"AMBIKCO",
				"VKSPL",
				"RAJRAYON",
				"GUJRATGAS",
				"LLOYDFIN",
				"MERCK",
				"IOLCP",
				"MTNL",
				"PREMIERPOL",
				"SHILPI",
				"EUROCERA",
				"SINTEX",
				"NAKODA",
				"VIJSHAN",
				"HINDDORROL",
				"COUNCODOS",
				"GUJALKALI",
				"SUJANAUNI",
				"MANDHANA",
				"AMLSTEEL",
				"IDBI",
				"20MICRONS",
				"DELTAMAGNT",
				"DICIND",
				"EMKAY",
				"TODAYS",
				"CNOVAPETRO",
				"PRAKASHCON",
				"IDEA",
				"OSWALMIN",
				"JINDCOT",
				"STARPAPER",
				"KRISHNAENG",
				"BODHTREE",
				"PATSPINLTD",
				"EIMCOELECO",
				"VMART",
				"ASHOKLEY",
				"ASIL",
				"PANCHSHEEL",
				"VIVIDHA",
				"ALCHEM",
				"SOTL",
				"OPTOCIRCUI",
				"INDLMETER",
				"PIRPHYTO",
				"AARTIIND",
				"CERA",
				"CRESTANI",
				"BLBLIMITED",
				"TANLA",
				"HOCL",
				"CESC",
				"TBZ",
				"KEYCORPSER",
				"KECL",
				"VAIBHAVGBL",
				"GUJAPOLLO",
				"CYBERMEDIA",
				"INDIAINFO",
				"NAVINFLUOR",
				"DEN",
				"PRESSMN",
				"OMAXE",
				"GRUH",
				"GSLNOVA",
				"INDHOTEL",
				"MINDACORP",
				"DHAMPURSUG",
				"SHASUNPHAR",
				"ARSHIYA",
				"BILPOWER",
				"ATNINTER",
				"NRC",
				"TRIL",
				"PIIND",
				"HORIZONINF",
				"ORBITCORP",
				"HINDSYNTEX",
				"VIKASGLOB",
				"REMSONSIND",
				"TULSI",
				"SREEL",
				"HIRAFERRO",
				"SHLAKSHMI",
				"INFODRIVE",
				"UNITY",
				"SRICHAMUND",
				"GREENFIRE",
				"MANGCHEFER",
				"CORPBANK",
				"SERVALL",
				"TCPLTD",
				"SHRIRAMCIT",
				"MAHINDCIE",
				"ORIENTABRA"
		};
		IntelliInvestStore.initialize();
//		for(String code :codes){
//			SignalGenerator.generateMagicNumber("ALL");
//		}
//		SignalGenerator.generateMagicNumber("ICICIBANK");
		SignalGenerator.generateSignals("HAVELLS");
		SignalGenerator.generateSignals("ICICIBANK");
//		SignalGenerator.generateSignals("SABTN");
//		SignalGenerator.generateTodaySignals("ALL");
//		SignalGenerator.generateTodaySignals("SABTN");
//		SignalGenerator.generateMagicNumber("ICICIBANK", 5);
//		SignalGenerator.generateSignals("ICICIBANK", 5);
		
//		SignalGenerator.generateMagicNumber("ICICIBANK", 10);
//		SignalGenerator.generateSignals("ICICIBANK", 10);
//		SignalGenerator.generateTodaySignals("ICICIBANK", 10);
//		SignalGenerator.generateMagicNumber("ICICIBANK", 15);
//		SignalGenerator.generateSignals("ICICIBANK", 15);
//		SignalGenerator.generateTodaySignals("ICICIBANK", 15);
		System.exit(0);
	}
}
